version: '3'
services:
  book-api:
    build: .
    ports:
      - "3000:3000"

#  db:
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: book_db